"""stream reviewers

Revision ID: 6f49614ce317
Revises: d18872e47591
Create Date: 2026-09-06 00:52:26.397122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f49614ce317'
down_revision: Union[str, Sequence[str], None] = 'd18872e47591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_reviewers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stream_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_id', 'reviewer_id', name='uq_stream_reviewers_stream_reviewer')
    )
    op.create_index(op.f('ix_stream_reviewers_reviewer_id'), 'stream_reviewers', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_stream_reviewers_stream_id'), 'stream_reviewers', ['stream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_reviewers_stream_id'), table_name='stream_reviewers')
    op.drop_index(op.f('ix_stream_reviewers_reviewer_id'), table_name='stream_reviewers')
    op.drop_table('stream_reviewers')
    # ### end Alembic commands ###
