"""courses, streams, assignments, enrollments

Revision ID: d18872e47591
Revises: c3f1a7d20b45
Create Date: 2026-09-06 00:09:20.544301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18872e47591'
down_revision: Union[str, Sequence[str], None] = 'c3f1a7d20b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Курс, поток, задание и зачисление.

    Задание — это рубрика, выданная потоку в срок: требования остаются в
    файле рубрики, расписание живёт здесь. У сдачи появляются `assignment_id`
    и `student_id`, оба необязательные — разбор по прямой ссылке на рубрику,
    без потока и без заведённого студента, продолжает работать.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_key'), 'courses', ['key'], unique=True)
    op.create_table('streams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'key', name='uq_streams_course_key')
    )
    op.create_index(op.f('ix_streams_course_id'), 'streams', ['course_id'], unique=False)
    op.create_index(op.f('ix_streams_key'), 'streams', ['key'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stream_id', sa.Uuid(), nullable=False),
    sa.Column('rubric_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_id', 'rubric_key', name='uq_assignments_stream_rubric')
    )
    op.create_index(op.f('ix_assignments_rubric_key'), 'assignments', ['rubric_key'], unique=False)
    op.create_index(op.f('ix_assignments_stream_id'), 'assignments', ['stream_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stream_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_id', 'student_id', name='uq_enrollments_stream_student')
    )
    op.create_index(op.f('ix_enrollments_stream_id'), 'enrollments', ['stream_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    # Через batch, а не голым ALTER: автоген выдал безымянные внешние ключи,
    # а SQLite их не умеет — ни создать, ни потом уронить по имени. Тесты
    # гоняют миграции именно на SQLite, поэтому расхождение вылезло бы не на
    # ревью, а на первом же прогоне. Имена заданы явно по той же причине.
    with op.batch_alter_table("submissions") as batch:
        batch.add_column(sa.Column("assignment_id", sa.Uuid(), nullable=True))
        batch.add_column(sa.Column("student_id", sa.Uuid(), nullable=True))
        batch.create_foreign_key(
            "fk_submissions_assignment_id", "assignments", ["assignment_id"], ["id"]
        )
        batch.create_foreign_key("fk_submissions_student_id", "users", ["student_id"], ["id"])
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    with op.batch_alter_table("submissions") as batch:
        batch.drop_constraint("fk_submissions_student_id", type_="foreignkey")
        batch.drop_constraint("fk_submissions_assignment_id", type_="foreignkey")
        batch.drop_column("student_id")
        batch.drop_column("assignment_id")
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_stream_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_assignments_stream_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_rubric_key'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_streams_key'), table_name='streams')
    op.drop_index(op.f('ix_streams_course_id'), table_name='streams')
    op.drop_table('streams')
    op.drop_index(op.f('ix_courses_key'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
