/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return ``ok`` while the process is running. Touches no dependencies.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Startup status
         * @description Service version, the ingest providers wired at startup, and the model route.
         */
        get: operations["init_init_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch a submission and return its canonical bundle
         * @description Resolve ``source`` to a provider, fetch the submission behind ``link`` and
         *     return the ``SubmissionBundle``: the change under review plus a compact repo map,
         *     sized to hand to an LLM. Full file bodies are not inlined — an agent pulls them
         *     later via ``Artifact.content_ref``.
         *
         *     ``422`` — link malformed or source unknown. ``502`` — the provider's upstream failed.
         */
        post: operations["ingest_submission_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rubrics available to review against
         * @description Каталог рубрик. Добавить курс — значит положить рядом ещё один JSON.
         */
        get: operations["list_rubrics_rubrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/{assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One rubric in full
         * @description Критерии, якоря и шкала — то, против чего ставился каждый вердикт.
         */
        get: operations["get_rubric_rubrics__assignment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn an assignment condition into a rubric draft
         * @description Разобрать условие задания и предложить рубрику.
         *
         *     Результат — черновик, а не рубрика: он не сохраняется в каталог и не
         *     участвует в проверках, пока методист его не подтвердит. Это единственное
         *     место конвейера, где ошибка модели тиражируется на весь поток, поэтому
         *     человек в цикле обязателен по устройству, а не по настройке.
         *
         *     Каждый критерий несёт цитату из условия, сверенную с текстом программно;
         *     `grounded_share` показывает, какая доля критериев подтверждена дословно.
         *     Всё, чего в условии нет — шкала, порог, штрафы, — не выдумывается, а
         *     выносится в `open_questions`.
         *
         *     ``502`` — модель не ответила или вернула неразбираемое.
         */
        post: operations["compile_rubric_rubrics_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft a review of a submission against a rubric
         * @description Собрать сдачу по ссылке и вернуть черновик ревью с проверенными цитатами.
         *
         *     Балл считает код, а не модель: она отвечает по каждому критерию отдельно и
         *     обязана приложить цитату, которая затем сверяется с текстом файла.
         *     Вердикты без подтверждённой цитаты помечены `needs_human_attention`.
         *
         *     ``404`` — рубрика не найдена. ``422`` — ссылка или источник неверны.
         *     ``502`` — источник сдачи не ответил.
         */
        post: operations["review_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Look for signs of generative-AI authorship
         * @description Ансамбль из четырёх сигналов: форензика истории, стилометрия, перплексия, judge.
         *
         *     Вывод рекомендательный. Он не является доказательством, на балл не влияет
         *     и содержит явный список того, чего проверка не видела: недоступные сигналы
         *     и файлы, доступные только фрагментом.
         */
        post: operations["detect_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model spend since startup
         * @description Журнал шлюза в цифрах: сколько вызовов ушло наружу, сколько это стоило.
         */
        get: operations["cost_cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Artifact
         * @description One reviewable unit of the submission: a source file, a notebook, a document.
         *
         *     Deliberately token-cheap: ``diff`` carries the change, ``excerpt`` carries the
         *     whole text only when it is small, and larger bodies are left out and fetched
         *     later through ``content_ref`` (see the field note).
         */
        Artifact: {
            /** Path */
            path: string;
            /** Previous Path */
            previous_path?: string | null;
            status: components["schemas"]["ChangeStatus"];
            /** @default solution */
            role: components["schemas"]["ArtifactRole"];
            /** Lang */
            lang?: string | null;
            /**
             * Is Binary
             * @default false
             */
            is_binary: boolean;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /** Line Count */
            line_count?: number | null;
            /** Changed Ranges */
            changed_ranges?: components["schemas"]["LineRange"][];
            /** Diff */
            diff?: string | null;
            /** Excerpt */
            excerpt?: string | null;
            /** Content Ref */
            content_ref?: string | null;
        };
        /**
         * ArtifactRole
         * @description Coarse purpose of an artifact so the review agent can skip what it need not read.
         *
         *     Assigned heuristically by ingest; a later classifier pass may refine it.
         * @enum {string}
         */
        ArtifactRole: "solution" | "evidence" | "tooling" | "noise";
        /**
         * ArtifactTextOut
         * @description Текст артефакта в том виде, в котором его видела модель.
         *
         *     Ровно то, что нужно панели файлов: цитата с номерами строк подсвечивается
         *     в этом тексте и ни в чём другом. `partial` говорит ревьюеру, что файл
         *     показан не целиком — и что вывод «этого в работе нет» здесь ненадёжен.
         */
        ArtifactTextOut: {
            /** Path */
            path: string;
            role: components["schemas"]["ArtifactRole"];
            /** Lang */
            lang: string | null;
            /** Partial */
            partial: boolean;
            /**
             * Origin
             * @description excerpt | fetched | diff — откуда взялся текст
             */
            origin: string;
            /** First Line */
            first_line: number;
            /** Last Line */
            last_line: number;
            /**
             * Line Numbers
             * @description Номер каждой строки `text` в полной версии файла. У фрагмента из диффа они идут с пропусками, поэтому нумеровать вьювером от `first_line` нельзя — цитата уедет на чужую строку.
             */
            line_numbers: number[];
            /**
             * Changed Lines
             * @description строки этой сдачи, например «1–48, 120»
             */
            changed_lines: string;
            /** Text */
            text: string;
        };
        /**
         * ChangeStatus
         * @description What happened to an artifact between ``base_ref`` and ``head_ref``.
         * @enum {string}
         */
        ChangeStatus: "added" | "modified" | "removed" | "renamed";
        /** CheckOutcome */
        CheckOutcome: {
            /** Check */
            check: string;
            /**
             * Level
             * @enum {string}
             */
            level: "blocking" | "warning" | "info";
            /** Label */
            label: string;
            /** Passed */
            passed: boolean;
            /**
             * Inconclusive
             * @default false
             */
            inconclusive: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Locations */
            locations?: string[];
        };
        /**
         * CompileRubricRequest
         * @description Условие задания, из которого нужно собрать черновик рубрики.
         */
        CompileRubricRequest: {
            /** Assignment Id */
            assignment_id: string;
            /**
             * Condition Text
             * @description текст условия целиком
             */
            condition_text: string;
            /**
             * Course
             * @default
             */
            course: string;
            /**
             * Hint
             * @description пожелание методиста: шкала, акценты, что учесть
             * @default
             */
            hint: string;
        };
        /**
         * CompileRubricResponse
         * @description Черновик рубрики. Не установлен и не сохранён — это предложение методисту.
         *
         *     `grounded_share` — доля критериев, подтверждённых дословной цитатой из
         *     условия. Всё, что ниже единицы, требует прочтения человеком в первую
         *     очередь: там модель пересказала, а не процитировала.
         */
        CompileRubricResponse: {
            draft: components["schemas"]["RubricDraft"];
            /** Grounded Share */
            grounded_share: number;
        };
        /**
         * CostSummary
         * @description Сводка обращений к моделям с момента старта — для карточки экономики прогона.
         */
        CostSummary: {
            /** Calls */
            calls: number;
            /** External Calls */
            external_calls: number;
            /** Errors */
            errors: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Redactions */
            redactions: number;
            /** Cost Rub */
            cost_rub: number;
        };
        /** Criterion */
        Criterion: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Max Score */
            max_score: number;
            /** Min Score For Pass */
            min_score_for_pass?: number | null;
            /**
             * Weight
             * @default 1
             */
            weight: number;
            /**
             * Description
             * @default
             */
            description: string;
            /** Checks */
            checks?: string[];
            /** Anchors */
            anchors?: {
                [key: string]: string;
            };
            /**
             * Evidence Required
             * @default true
             */
            evidence_required: boolean;
            /**
             * Auto Verifiable
             * @default false
             */
            auto_verifiable: boolean;
            /**
             * Ai Sensitive
             * @default false
             */
            ai_sensitive: boolean;
        };
        /**
         * CriterionSource
         * @description Откуда в рубрике взялся критерий.
         */
        CriterionSource: {
            /** Criterion Id */
            criterion_id: string;
            /**
             * Quote
             * @default
             */
            quote: string;
            /** @default missing */
            status: components["schemas"]["SourceStatus"];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * CriterionVerdict
         * @description Оценка одного критерия.
         *
         *     Обратите внимание, чего здесь нет: итогового балла работы. Модель
         *     оценивает критерии по отдельности, а сумму считает агрегатор — арифметику
         *     ей не доверяем.
         */
        CriterionVerdict: {
            /** Criterion Id */
            criterion_id: string;
            /**
             * Score
             * @description балл по этому критерию, не выше максимума
             */
            score: number;
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /**
             * Verdict
             * @description одно-два предложения: что именно сделано и что нет
             */
            verdict: string;
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /**
             * Student Feedback
             * @description формулировка для студента в поддерживающем тоне
             * @default
             */
            student_feedback: string;
            /**
             * Improvement Hint
             * @description что конкретно докрутить
             * @default
             */
            improvement_hint: string;
            /**
             * Needs Human Attention
             * @default false
             */
            needs_human_attention: boolean;
            /**
             * Attention Reason
             * @default
             */
            attention_reason: string;
        };
        /** DetectRequest */
        DetectRequest: {
            /** Link */
            link: string;
            /** @default github_pr */
            source: components["schemas"]["SubmissionSource"];
            /** Assignment Id */
            assignment_id?: string | null;
            /** Deadline At */
            deadline_at?: string | null;
            /** Student Internal Id */
            student_internal_id?: string | null;
            /**
             * Student Name
             * @description ФИО студента, если платформа его знает. Не уходит в модель: шлюз вычищает его вместе с падежами и инициалами. В бандле имени нет намеренно, поэтому без этого поля оно остаётся на общих детекторах.
             */
            student_name?: string | null;
            /** Rubric Id */
            rubric_id?: string | null;
        };
        /** DetectResponse */
        DetectResponse: {
            bundle: components["schemas"]["SubmissionBundle"];
            /** Files */
            files: components["schemas"]["ArtifactTextOut"][];
            report: components["schemas"]["DetectionReport"];
        };
        /** DetectionReport */
        DetectionReport: {
            /**
             * Overall Score
             * @default 0
             */
            overall_score: number;
            /**
             * Confidence Low
             * @default 0
             */
            confidence_low: number;
            /**
             * Confidence High
             * @default 0
             */
            confidence_high: number;
            /**
             * Label
             * @default недостаточно данных
             */
            label: string;
            /** Signals */
            signals?: components["schemas"]["SignalResult"][];
            /** Spans */
            spans?: components["schemas"]["Span"][];
            /** Limitations */
            limitations?: string[];
            /** Declared Ai Usage */
            declared_ai_usage?: boolean | null;
            /**
             * Declaration Note
             * @default
             */
            declaration_note: string;
            /**
             * Tokens In
             * @default 0
             */
            tokens_in: number;
            /**
             * Tokens Out
             * @default 0
             */
            tokens_out: number;
            /**
             * Cost Rub
             * @default 0
             */
            cost_rub: number;
            /**
             * Advisory
             * @default true
             */
            advisory: boolean;
            /**
             * Advisory Note
             * @default Сигнал носит рекомендательный характер, не является доказательством нарушения и не влияет на балл автоматически. Решение принимает ревьюер.
             */
            advisory_note: string;
            /**
             * Mismatch
             * @description Сигнал есть, а декларации нет — главный случай для ревьюера.
             *
             *     По условию курса запрещено не использование ИИ, а несогласованное
             *     использование: «Если вы использовали ИИ — укажите это в работе».
             *     Поэтому интересно не «сгенерировано или нет», а расхождение между
             *     заявленным и найденным.
             */
            readonly mismatch: boolean;
        };
        /**
         * Evidence
         * @description Цитата, на которую опирается вердикт.
         *
         *     Модель обязана указать не только файл, но и строки, и сам текст: без
         *     текста нечего сверять, без строк нечего подсвечивать в интерфейсе.
         */
        Evidence: {
            /**
             * Artifact
             * @description путь к файлу в сдаче
             */
            artifact: string;
            /**
             * Start Line
             * @description номер первой строки
             */
            start_line?: number | null;
            /**
             * End Line
             * @description номер последней строки
             */
            end_line?: number | null;
            /**
             * Quote
             * @description дословный фрагмент из файла
             * @default
             */
            quote: string;
            /** @default empty */
            status: components["schemas"]["EvidenceStatus"];
            /** Char Start */
            char_start?: number | null;
            /** Char End */
            char_end?: number | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        EvidenceStatus: "valid" | "wrong_location" | "not_in_available_part" | "no_such_artifact" | "empty";
        /**
         * FormatCheck
         * @description Формальное требование из условия — проверяется кодом, без единого токена.
         *
         *     Format Gate ещё не построен; рубрики уже несут его правила, потому что
         *     вынимать их из условия надо один раз вместе с критериями, а не потом.
         */
        FormatCheck: {
            /** Check */
            check: string;
            /**
             * Level
             * @default warning
             * @enum {string}
             */
            level: "blocking" | "warning" | "info";
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** GateReport */
        GateReport: {
            /** @default passed */
            status: components["schemas"]["GateStatus"];
            /** Outcomes */
            outcomes?: components["schemas"]["CheckOutcome"][];
            /** Facts */
            facts?: string[];
        };
        /**
         * GateStatus
         * @enum {string}
         */
        GateStatus: "passed" | "warning" | "blocked";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Link */
            link: string;
            /** @default github_pr */
            source: components["schemas"]["SubmissionSource"];
            /** Assignment Id */
            assignment_id?: string | null;
            /** Deadline At */
            deadline_at?: string | null;
            /** Student Internal Id */
            student_internal_id?: string | null;
        };
        /** InitResponse */
        InitResponse: {
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Sources */
            sources: components["schemas"]["SubmissionSource"][];
            /** Llm Provider */
            llm_provider: string;
            /** Rubrics */
            rubrics: string[];
        };
        /**
         * LatePolicy
         * @description Штраф за просрочку — правило из условия, а не наша выдумка.
         *
         *     «Досдача в течение 1 дня после дедлайна — −1 балл; позже — 0 баллов»
         *     ложится сюда как `grace_days=1, penalty_per_grace_day=1, after_grace=zero`.
         */
        LatePolicy: {
            /**
             * Grace Days
             * @default 0
             */
            grace_days: number;
            /**
             * Penalty Per Grace Day
             * @default 0
             */
            penalty_per_grace_day: number;
            /**
             * After Grace
             * @default zero
             * @enum {string}
             */
            after_grace: "zero" | "continue";
        };
        /**
         * LineRange
         * @description Inclusive, 1-based line span on the head version of an artifact.
         */
        LineRange: {
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /**
         * RepoContext
         * @description Compact map of the surrounding codebase. ``None`` for non-repository sources.
         *
         *     This is only an inventory of what exists, not the code itself. Any path here (or,
         *     when ``truncated``, any path at all) is fetched the same way as an artifact body:
         *     the review layer's ``get_file(path)`` tool resolves it against ``root`` and the
         *     bundle's ``head_ref``.
         */
        RepoContext: {
            /** Root */
            root?: string | null;
            /** Default Branch */
            default_branch?: string | null;
            /**
             * Total Files
             * @default 0
             */
            total_files: number;
            /** Files */
            files?: string[];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /**
         * ReviewDraft
         * @description Черновик, который увидит ревьюер.
         */
        ReviewDraft: {
            /** Assignment Id */
            assignment_id: string;
            /**
             * Rubric Title
             * @default
             */
            rubric_title: string;
            /** Verdicts */
            verdicts?: components["schemas"]["CriterionVerdict"][];
            /**
             * Raw Score
             * @default 0
             */
            raw_score: number;
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Max Score
             * @default 0
             */
            max_score: number;
            /**
             * Passed
             * @default false
             */
            passed: boolean;
            /**
             * Pass Explanation
             * @default
             */
            pass_explanation: string;
            /**
             * Late Explanation
             * @default
             */
            late_explanation: string;
            /** Gate Facts */
            gate_facts?: string[];
            gate?: components["schemas"]["GateReport"] | null;
            /**
             * Needs Human Attention
             * @default false
             */
            needs_human_attention: boolean;
            /** Attention Reasons */
            attention_reasons?: string[];
            /** Partial Artifacts */
            partial_artifacts?: string[];
            /**
             * Tokens In
             * @default 0
             */
            tokens_in: number;
            /**
             * Tokens Out
             * @default 0
             */
            tokens_out: number;
            /**
             * Cost Rub
             * @default 0
             */
            cost_rub: number;
            /** Failed Criteria */
            failed_criteria?: string[];
            /**
             * Evidence Coverage
             * @description Доля вердиктов, подкреплённых проверенной цитатой.
             */
            readonly evidence_coverage: number;
        };
        /**
         * ReviewRequest
         * @description Запрос на черновик ревью.
         *
         *     Рубрика приходит либо по идентификатору из каталога, либо целиком в теле —
         *     второе нужно, пока Rubric Compiler отдаёт её на подтверждение методисту и
         *     в каталоге её ещё нет.
         */
        ReviewRequest: {
            /** Link */
            link: string;
            /** @default github_pr */
            source: components["schemas"]["SubmissionSource"];
            /** Assignment Id */
            assignment_id?: string | null;
            /** Deadline At */
            deadline_at?: string | null;
            /** Student Internal Id */
            student_internal_id?: string | null;
            /**
             * Student Name
             * @description ФИО студента, если платформа его знает. Не уходит в модель: шлюз вычищает его вместе с падежами и инициалами. В бандле имени нет намеренно, поэтому без этого поля оно остаётся на общих детекторах.
             */
            student_name?: string | null;
            /** Rubric Id */
            rubric_id?: string | null;
            rubric?: components["schemas"]["Rubric"] | null;
            /**
             * Condition Text
             * @default
             */
            condition_text: string;
            /**
             * Gate Facts
             * @description Факты Format Gate: проверены кодом, модель их не пересчитывает
             */
            gate_facts?: string[];
        };
        /**
         * ReviewResponse
         * @description Всё, что нужно рабочему месту ревьюера за один запрос.
         *
         *     Сдача, тексты файлов и черновик приходят вместе намеренно: разложить это
         *     на три вызова значило бы три раза сходить в GitHub за одним и тем же.
         */
        ReviewResponse: {
            bundle: components["schemas"]["SubmissionBundle"];
            /** Files */
            files: components["schemas"]["ArtifactTextOut"][];
            draft: components["schemas"]["ReviewDraft"];
        };
        /**
         * ReviewerVerdict
         * @enum {string}
         */
        ReviewerVerdict: "pending" | "confirmed" | "rejected";
        /**
         * Revision
         * @description One entry of the submission's revision history (a commit). Feeds AI-detection forensics.
         */
        Revision: {
            /** Id */
            id: string;
            /**
             * Authored At
             * Format: date-time
             */
            authored_at: string;
            /** Author Hash */
            author_hash: string;
            /** Summary */
            summary?: string | null;
            /**
             * Added Lines
             * @default 0
             */
            added_lines: number;
            /**
             * Removed Lines
             * @default 0
             */
            removed_lines: number;
        };
        /** Rubric */
        Rubric: {
            /** Assignment Id */
            assignment_id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Course
             * @default
             */
            course: string;
            /** Stage */
            stage?: string | null;
            /**
             * Source Note
             * @default
             */
            source_note: string;
            /**
             * Ai Policy
             * @default declare_required
             */
            ai_policy: string;
            scale: components["schemas"]["Scale"];
            late_policy?: components["schemas"]["LatePolicy"];
            /** Format Gate */
            format_gate?: components["schemas"]["FormatCheck"][];
            /** Criteria */
            criteria?: components["schemas"]["Criterion"][];
        };
        /**
         * RubricDraft
         * @description Предложение компилятора. Рубрикой становится после подтверждения методистом.
         */
        RubricDraft: {
            rubric: components["schemas"]["Rubric"];
            /** Sources */
            sources?: components["schemas"]["CriterionSource"][];
            /** Warnings */
            warnings?: string[];
            /** Open Questions */
            open_questions?: string[];
            /**
             * Tokens In
             * @default 0
             */
            tokens_in: number;
            /**
             * Tokens Out
             * @default 0
             */
            tokens_out: number;
            /**
             * Cost Rub
             * @default 0
             */
            cost_rub: number;
        };
        /** RubricSummary */
        RubricSummary: {
            /** Assignment Id */
            assignment_id: string;
            /** Title */
            title: string;
            /** Course */
            course: string;
            /** Stage */
            stage: string | null;
            /** Criteria */
            criteria: number;
            /** Total Max */
            total_max: number;
            /** Pass Threshold */
            pass_threshold: number | null;
        };
        /**
         * Scale
         * @description Шкала задания: максимум, порог зачёта и шаг округления.
         */
        Scale: {
            /** Total Max */
            total_max: number;
            /** Pass Threshold */
            pass_threshold?: number | null;
            /**
             * Step
             * @default 1
             */
            step: number;
        };
        /**
         * SignalKind
         * @enum {string}
         */
        SignalKind: "forensics" | "perplexity" | "stylometry" | "judge";
        /** SignalResult */
        SignalResult: {
            kind: components["schemas"]["SignalKind"];
            /** @default ok */
            status: components["schemas"]["SignalStatus"];
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Weight
             * @default 0
             */
            weight: number;
            /** Spans */
            spans?: components["schemas"]["Span"][];
            /** Findings */
            findings?: string[];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * SignalStatus
         * @enum {string}
         */
        SignalStatus: "ok" | "unavailable" | "failed";
        /**
         * SourceStatus
         * @enum {string}
         */
        SourceStatus: "quoted" | "paraphrased" | "missing";
        /**
         * Span
         * @description Подозрительный фрагмент.
         *
         *     Номера строк — в координатах полной версии файла, той же, что у цитат
         *     ревью: клик по спану в правой панели подсвечивает те же строки в левой.
         *     Смещения в символах есть только у файлов, доступных целиком — в тексте,
         *     собранном из диффа, они указывали бы в наш кусок, а не в файл.
         */
        Span: {
            /** Artifact */
            artifact: string;
            /** Start */
            start?: number | null;
            /** End */
            end?: number | null;
            /** Start Line */
            start_line?: number | null;
            /** End Line */
            end_line?: number | null;
            /** Score */
            score: number;
            /** Signals */
            signals?: components["schemas"]["SignalKind"][];
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /**
             * Ai Sensitive
             * @default false
             */
            ai_sensitive: boolean;
            /** @default pending */
            reviewer_verdict: components["schemas"]["ReviewerVerdict"];
            /** Id */
            readonly id: string;
        };
        /**
         * StudentRef
         * @description Pseudonymous author identity. Holds no real name and is safe to send to an LLM.
         */
        StudentRef: {
            /** Internal Id */
            internal_id: string;
            /** External Handles */
            external_handles?: {
                [key: string]: string;
            };
        };
        /**
         * SubmissionBundle
         * @description Canonical, provider-agnostic snapshot of one submission, sized to hand to an LLM.
         *
         *     Every stage after ingest (Format Gate, Assignment, Review Agent, AI-Detection)
         *     reads only this object. It carries the change under review plus just enough
         *     context to reason about it. Full file bodies are intentionally NOT here: the
         *     review layer exposes a ``get_file`` tool to the agent that resolves an
         *     ``Artifact.content_ref`` (or any repo path via ``head_ref``) on demand.
         */
        SubmissionBundle: {
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id?: string;
            source: components["schemas"]["SubmissionSource"];
            /** Origin Url */
            origin_url: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            student_ref: components["schemas"]["StudentRef"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Deadline At */
            deadline_at?: string | null;
            /** Assignment Id */
            assignment_id?: string | null;
            /** Base Ref */
            base_ref?: string | null;
            /** Head Ref */
            head_ref?: string | null;
            /** Artifacts */
            artifacts?: components["schemas"]["Artifact"][];
            /** Revisions */
            revisions?: components["schemas"]["Revision"][];
            repo?: components["schemas"]["RepoContext"] | null;
        };
        /**
         * SubmissionSource
         * @description The input provider a submission was fetched from. One value per provider.
         * @enum {string}
         */
        SubmissionSource: "github_pr";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    init_init_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitResponse"];
                };
            };
        };
    };
    ingest_submission_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description The canonical SubmissionBundle for the linked submission */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rubrics_rubrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricSummary"][];
                };
            };
        };
    };
    get_rubric_rubrics__assignment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rubric"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_rubric_rubrics_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRubricRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileRubricResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_cost_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostSummary"];
                };
            };
        };
    };
}
